version: '2'
networks:
   mysql_net:
     driver: bridge
services:
  cromwell:
    image: "${CROMWELL_DOCKER_IMAGE}"
    volumes:
      - ${CROMWELL_CONF_DIR}:/conf
    environment:
      - CROMWELL_PROJECT
      - CROMWELL_EXECUTION_ROOT
      - CLOUD_SQL_DB_USER
      - CLOUD_SQL_DB_PASSWORD
      - TEST_CASE_DIRECTORY
      - JAVA_OPTS=-Dconfig.file=/conf/cromwell.conf
    command: ["server"]
    depends_on:
      - cloudsql-db
    ports:
      - "8000:8000"
    networks:
      mysql_net:
    container_name: cromwell
  cloudsql-db:
    # Be careful if upgrading this, the `nc` used in `healthcheck` disappeared from newer versions.
    # https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/137#issuecomment-598188268
    # Health checks do appear to be necessary to prevent Cromwell from occasionally wedging itself on startup,
    # but there doesn't appear to be a Google-blessed way of performing them.
    image: "gcr.io/cloudsql-docker/gce-proxy:1.11"
    ports:
      - "127.0.0.1:3306:3306"
    container_name: cloudsql-db
    command: ["/cloud_sql_proxy", "-instances=broad-dsde-cromwell-perf:us-central1:${CLOUD_SQL_INSTANCE}=tcp:0.0.0.0:3306"]
    healthcheck:
      test: "/usr/bin/nc 127.0.0.1 3306"
    networks:
      mysql_net:
